[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

# Next.js 표준 배포 설정: 추가 컨텍스트 강제 설정 제거

# 리다이렉트 설정 (네이버 블로그 카드 방지용)
[[redirects]]
  from = "/blog"
  to = "/"
  status = 301

# 불필요한 SPA 강제 리다이렉트 제거 (Next.js 라우팅 방해)

[[redirects]]
  from = "/naver"
  to = "/"
  status = 301

[[redirects]]
  from = "/banner"
  to = "/"
  status = 301