[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"

# Force static site deployment
[context.production]
  publish = "out"
  command = "npm run build"

[context.deploy-preview]
  publish = "out"
  command = "npm run build"

# 리다이렉트 설정 (네이버 블로그 카드 방지용)
[[redirects]]
  from = "/blog"
  to = "/"
  status = 301


# 전체 도메인 이동: 새 도메인으로 301 리다이렉트
[[redirects]]
  from = "/*"
  to = "https://www.lslsjsjslololo1455.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/naver"
  to = "/"
  status = 301

[[redirects]]
  from = "/banner"
  to = "/"
  status = 301